// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfjicwlopcwjjvojmgow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpmamljd2xvcGN3amp2b2ptZ293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTgwMjYsImV4cCI6MjA3MDIzNDAyNn0.aVSihcmt12SVSyPFPWh8cNPXylOeB5vxXoSjstO5HqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});